services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - '8080:80'
      - '8465:25'
    environment:
      - ServerOptions__HostName=localhost
      - ServerOptions__TlsMode=ImplicitTls
